"""Dữ liệu mẫu tỉnh Cao Bằng.

- 56 xã/phường theo Nghị quyết 1657/NQ-UBTVQH15 (hiệu lực 01/07/2025). Toạ độ là TÂM XẤP XỈ;
  ranh giới xã được sinh bằng Voronoi và cắt theo ranh giới tỉnh → chỉ dùng cho mô phỏng.
- Trạm quan trắc, hồ chứa, lực lượng, kho, danh bạ, số điện thoại… là DỮ LIỆU MINH HOẠ,
  cần thay bằng dữ liệu chính thức của Sở NN&MT / BCH PCTT & TKCN tỉnh khi triển khai thật.
"""

import unicodedata


def slug(name: str) -> str:
    s = name.replace("đ", "d").replace("Đ", "D")
    s = unicodedata.normalize("NFD", s)
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return "".join(c for c in s.upper() if c.isalnum())


def unit_code(name: str) -> str:
    return f"CB-{slug(name)}"


# (tên, loại, địa bàn huyện cũ, vĩ độ, kinh độ)
COMMUNES: list[tuple[str, str, str, float, float]] = [
    # TP. Cao Bằng cũ
    ("Thục Phán", "phuong", "TP. Cao Bằng", 22.676, 106.250),
    ("Nùng Trí Cao", "phuong", "TP. Cao Bằng", 22.662, 106.282),
    ("Tân Giang", "phuong", "TP. Cao Bằng", 22.628, 106.285),
    # Hòa An
    ("Hòa An", "xa", "Hòa An", 22.722, 106.182),
    ("Nam Tuấn", "xa", "Hòa An", 22.700, 106.098),
    ("Bạch Đằng", "xa", "Hòa An", 22.748, 106.232),
    ("Nguyễn Huệ", "xa", "Hòa An", 22.615, 106.195),
    ("Minh Khai", "xa", "Thạch An", 22.610, 106.372),
    ("Canh Tân", "xa", "Thạch An", 22.560, 106.335),
    ("Kim Đồng", "xa", "Thạch An", 22.505, 106.380),
    ("Thạch An", "xa", "Thạch An", 22.575, 106.440),
    # Thạch An
    ("Đông Khê", "xa", "Thạch An", 22.432, 106.432),
    ("Đức Long", "xa", "Thạch An", 22.372, 106.545),
    ("Phục Hòa", "xa", "Quảng Hòa", 22.500, 106.580),
    ("Bế Văn Đàn", "xa", "Quảng Hòa", 22.605, 106.505),
    # Quảng Hòa
    ("Quảng Uyên", "xa", "Quảng Hòa", 22.692, 106.440),
    ("Độc Lập", "xa", "Quảng Hòa", 22.752, 106.465),
    ("Hạnh Phúc", "xa", "Quảng Hòa", 22.650, 106.525),
    ("Quang Hán", "xa", "Trùng Khánh", 22.800, 106.405),
    # Trùng Khánh (gồm Trà Lĩnh cũ)
    ("Trà Lĩnh", "xa", "Trùng Khánh", 22.820, 106.318),
    ("Quang Trung", "xa", "Trùng Khánh", 22.872, 106.375),
    ("Trùng Khánh", "xa", "Trùng Khánh", 22.830, 106.520),
    ("Đoài Dương", "xa", "Trùng Khánh", 22.775, 106.585),
    ("Đàm Thủy", "xa", "Trùng Khánh", 22.850, 106.705),
    ("Đình Phong", "xa", "Trùng Khánh", 22.905, 106.605),
    # Hạ Lang
    ("Hạ Lang", "xa", "Hạ Lang", 22.708, 106.668),
    ("Lý Quốc", "xa", "Hạ Lang", 22.742, 106.785),
    ("Vinh Quý", "xa", "Hạ Lang", 22.655, 106.715),
    ("Quang Long", "xa", "Hạ Lang", 22.690, 106.600),
    # Hà Quảng
    ("Thông Nông", "xa", "Hà Quảng", 22.790, 105.985),
    ("Cần Yên", "xa", "Hà Quảng", 22.845, 106.060),
    ("Thanh Long", "xa", "Hà Quảng", 22.815, 105.895),
    ("Hà Quảng", "xa", "Hà Quảng", 22.935, 106.125),
    ("Trường Hà", "xa", "Hà Quảng", 22.905, 106.070),
    ("Lũng Nặm", "xa", "Hà Quảng", 22.985, 106.020),
    ("Tổng Cọt", "xa", "Hà Quảng", 22.975, 106.190),
    # Nguyên Bình
    ("Nguyên Bình", "xa", "Nguyên Bình", 22.655, 105.955),
    ("Tĩnh Túc", "xa", "Nguyên Bình", 22.640, 105.870),
    ("Minh Tâm", "xa", "Nguyên Bình", 22.585, 106.020),
    ("Phan Thanh", "xa", "Nguyên Bình", 22.730, 105.760),
    ("Thành Công", "xa", "Nguyên Bình", 22.590, 105.835),
    ("Tam Kim", "xa", "Nguyên Bình", 22.625, 106.075),
    ("Ca Thành", "xa", "Nguyên Bình", 22.685, 105.640),
    # Bảo Lạc
    ("Bảo Lạc", "xa", "Bảo Lạc", 22.950, 105.672),
    ("Hưng Đạo", "xa", "Bảo Lạc", 22.920, 105.560),
    ("Cốc Pàng", "xa", "Bảo Lạc", 23.050, 105.600),
    ("Cô Ba", "xa", "Bảo Lạc", 22.905, 105.775),
    ("Khánh Xuân", "xa", "Bảo Lạc", 22.820, 105.700),
    ("Xuân Trường", "xa", "Bảo Lạc", 23.040, 105.715),
    ("Huy Giáp", "xa", "Bảo Lạc", 22.850, 105.590),
    # Bảo Lâm
    ("Bảo Lâm", "xa", "Bảo Lâm", 22.862, 105.475),
    ("Lý Bôn", "xa", "Bảo Lâm", 22.735, 105.430),
    ("Nam Quang", "xa", "Bảo Lâm", 22.785, 105.535),
    ("Quảng Lâm", "xa", "Bảo Lâm", 22.890, 105.365),
    ("Yên Thổ", "xa", "Bảo Lâm", 22.620, 105.520),
    ("Sơn Lộ", "xa", "Bảo Lâm", 22.985, 105.450),
]

OLD_DISTRICTS = [
    "TP. Cao Bằng",
    "Hòa An",
    "Thạch An",
    "Quảng Hòa",
    "Trùng Khánh",
    "Hạ Lang",
    "Hà Quảng",
    "Nguyên Bình",
    "Bảo Lạc",
    "Bảo Lâm",
]

PRESETS = [
    (
        "LV_BANG_GIANG",
        "Vùng trũng & hạ lưu sông Bằng Giang – Hiến",
        "Các phường nội thị và xã ven sông Bằng Giang, sông Hiến — trọng điểm điều hành lũ, ngập úng đô thị.",
        "ngap_lut",
        [
            "Thục Phán",
            "Nùng Trí Cao",
            "Tân Giang",
            "Hòa An",
            "Bạch Đằng",
            "Nam Tuấn",
            "Nguyễn Huệ",
            "Canh Tân",
            "Phục Hòa",
        ],
    ),
    (
        "VUNG_NUI_CAO",
        "Vùng núi cao & đèo dốc phía Tây",
        "Bảo Lâm, Bảo Lạc, Nguyên Bình — đèo Khau Cốc Chà, Mẻ Pia, Cao Bắc: trọng điểm sạt lở đất, lũ quét.",
        "sat_lo",
        [c[0] for c in COMMUNES if c[2] in ("Bảo Lâm", "Bảo Lạc", "Nguyên Bình")],
    ),
    (
        "BIEN_GIOI",
        "Dải biên giới Việt – Trung",
        "Các xã biên giới có đồn Biên phòng — phối hợp BĐBP tỉnh trong cứu hộ và sơ tán.",
        "tong_hop",
        [
            "Cốc Pàng",
            "Xuân Trường",
            "Sơn Lộ",
            "Lũng Nặm",
            "Hà Quảng",
            "Tổng Cọt",
            "Trà Lĩnh",
            "Quang Trung",
            "Đình Phong",
            "Đàm Thủy",
            "Lý Quốc",
            "Phục Hòa",
            "Đức Long",
        ],
    ),
]

# ---------------------------------------------------------------------------
# Trạm quan trắc (id, tên, loại, sông, đơn vị, xã, lat, lon, ngưỡng, tham số kịch bản)
# Ngưỡng Báo động I/II/III là MINH HOẠ.
# Kịch bản: rain → cường độ đỉnh mm/h; wl → (mực nền, biên độ lũ); tilt → giá trị cực đại độ; soil → đỉnh %
# ---------------------------------------------------------------------------
STATIONS = [
    (
        "CB-WL-01",
        "Trạm thủy văn Cao Bằng (sông Bằng Giang)",
        "muc_nuoc",
        "Bằng Giang",
        "m",
        "Thục Phán",
        22.668,
        106.257,
        {"bd1": 180.0, "bd2": 181.0, "bd3": 182.0},
        {"base": 178.4, "amp": 3.4},
    ),
    (
        "CB-WL-02",
        "Trạm thủy văn Nà Phía (sông Hiến)",
        "muc_nuoc",
        "Hiến",
        "m",
        "Thục Phán",
        22.700,
        106.215,
        {"bd1": 184.5, "bd2": 185.5, "bd3": 186.5},
        {"base": 183.2, "amp": 2.6},
    ),
    (
        "CB-WL-03",
        "Trạm thủy văn Bảo Lạc (sông Gâm)",
        "muc_nuoc",
        "Gâm",
        "m",
        "Bảo Lạc",
        22.952,
        105.668,
        {"bd1": 212.0, "bd2": 214.0, "bd3": 216.0},
        {"base": 209.5, "amp": 5.2},
    ),
    (
        "CB-WL-04",
        "Trạm thủy văn Bản Giốc (sông Quây Sơn)",
        "muc_nuoc",
        "Quây Sơn",
        "m",
        "Đàm Thủy",
        22.853,
        106.716,
        {"bd1": 337.0, "bd2": 338.0, "bd3": 339.0},
        {"base": 335.8, "amp": 2.0},
    ),
    (
        "CB-WL-05",
        "Trạm thủy văn Quảng Uyên (sông Bắc Vọng)",
        "muc_nuoc",
        "Bắc Vọng",
        "m",
        "Quảng Uyên",
        22.690,
        106.448,
        {"bd1": 290.0, "bd2": 291.0, "bd3": 292.0},
        {"base": 288.8, "amp": 1.9},
    ),
    (
        "CB-RN-01",
        "Trạm đo mưa TP. Cao Bằng",
        "luong_mua",
        None,
        "mm/h",
        "Nùng Trí Cao",
        22.660,
        106.265,
        {},
        {"peak": 16},
    ),
    (
        "CB-RN-02",
        "Trạm đo mưa Nguyên Bình",
        "luong_mua",
        None,
        "mm/h",
        "Nguyên Bình",
        22.656,
        105.950,
        {},
        {"peak": 34},
    ),
    (
        "CB-RN-03",
        "Trạm đo mưa Phja Oắc (Tĩnh Túc)",
        "luong_mua",
        None,
        "mm/h",
        "Tĩnh Túc",
        22.610,
        105.880,
        {},
        {"peak": 42},
    ),
    (
        "CB-RN-04",
        "Trạm đo mưa Bảo Lạc",
        "luong_mua",
        None,
        "mm/h",
        "Bảo Lạc",
        22.948,
        105.680,
        {},
        {"peak": 30},
    ),
    (
        "CB-RN-05",
        "Trạm đo mưa Pác Miầu (Bảo Lâm)",
        "luong_mua",
        None,
        "mm/h",
        "Bảo Lâm",
        22.860,
        105.480,
        {},
        {"peak": 36},
    ),
    (
        "CB-RN-06",
        "Trạm đo mưa Hà Quảng",
        "luong_mua",
        None,
        "mm/h",
        "Trường Hà",
        22.900,
        106.075,
        {},
        {"peak": 22},
    ),
    (
        "CB-RN-07",
        "Trạm đo mưa Trùng Khánh",
        "luong_mua",
        None,
        "mm/h",
        "Trùng Khánh",
        22.832,
        106.525,
        {},
        {"peak": 19},
    ),
    (
        "CB-RN-08",
        "Trạm đo mưa Đông Khê",
        "luong_mua",
        None,
        "mm/h",
        "Đông Khê",
        22.435,
        106.430,
        {},
        {"peak": 14},
    ),
    (
        "CB-RN-09",
        "Trạm đo mưa Hạ Lang",
        "luong_mua",
        None,
        "mm/h",
        "Hạ Lang",
        22.708,
        106.672,
        {},
        {"peak": 17},
    ),
    (
        "CB-RN-10",
        "Trạm đo mưa Ca Thành",
        "luong_mua",
        None,
        "mm/h",
        "Ca Thành",
        22.688,
        105.645,
        {},
        {"peak": 38},
    ),
    (
        "CB-TL-01",
        "Cảm biến nghiêng đèo Khau Cốc Chà",
        "do_nghieng",
        None,
        "độ",
        "Khánh Xuân",
        22.805,
        105.722,
        {"bd1": 0.5, "bd2": 1.0, "bd3": 2.0},
        {"peak": 2.6},
    ),
    (
        "CB-TL-02",
        "Cảm biến nghiêng đèo Mẻ Pia",
        "do_nghieng",
        None,
        "độ",
        "Cô Ba",
        22.870,
        105.845,
        {"bd1": 0.5, "bd2": 1.0, "bd3": 2.0},
        {"peak": 1.2},
    ),
    (
        "CB-TL-03",
        "Cảm biến nghiêng taluy QL34 – Tĩnh Túc",
        "do_nghieng",
        None,
        "độ",
        "Tĩnh Túc",
        22.648,
        105.890,
        {"bd1": 0.5, "bd2": 1.0, "bd3": 2.0},
        {"peak": 0.8},
    ),
    (
        "CB-TL-04",
        "Cảm biến nghiêng đèo Mã Phục (QL3)",
        "do_nghieng",
        None,
        "độ",
        "Trà Lĩnh",
        22.770,
        106.285,
        {"bd1": 0.5, "bd2": 1.0, "bd3": 2.0},
        {"peak": 0.6},
    ),
    (
        "CB-SM-01",
        "Độ ẩm đất sườn đồi Pác Miầu",
        "do_am_dat",
        None,
        "%",
        "Bảo Lâm",
        22.868,
        105.470,
        {"bd1": 38, "bd2": 43, "bd3": 48},
        {"peak": 47},
    ),
    (
        "CB-SM-02",
        "Độ ẩm đất Phja Oắc – Phja Đén",
        "do_am_dat",
        None,
        "%",
        "Thành Công",
        22.598,
        105.845,
        {"bd1": 38, "bd2": 43, "bd3": 48},
        {"peak": 45},
    ),
]

# Trạm mưa đại diện cho từng lưu vực trạm mực nước (dùng cho kịch bản & dự báo)
RESERVOIRS = [
    # id, tên, sông, xã, MW, MNDBT, mực hiện tại, số cửa xả, lat, lon
    ("HC-BLB", "Thủy điện Bảo Lạc B", "Gâm", "Bảo Lạc", 150, 162.0, 160.8, 5, 22.965, 105.640),
    ("HC-BL1", "Thủy điện Bảo Lâm 1", "Gâm", "Lý Bôn", 30, 215.0, 213.9, 4, 22.760, 105.455),
    ("HC-BR", "Thủy điện Bản Rạ", "Neo", "Cô Ba", 18, 395.0, 393.6, 3, 22.915, 105.740),
    ("HC-HT", "Thủy điện Hòa Thuận", "Bằng Giang", "Phục Hòa", 38, 262.0, 261.2, 4, 22.535, 106.530),
    ("HC-BD", "Thủy điện Bạch Đằng", "Bằng Giang", "Bạch Đằng", 12, 196.0, 195.1, 3, 22.735, 106.245),
    ("HC-KL", "Hồ thủy lợi Khuổi Lái", "Suối Khuổi Lái", "Tam Kim", 0, 250.0, 249.2, 2, 22.640, 106.090),
]

CAMERAS = [
    ("CAM-01", "Cầu Bằng Giang – TP. Cao Bằng", "Thục Phán", 22.667, 106.259),
    ("CAM-02", "Cầu Hoàng Ngà – sông Hiến", "Nùng Trí Cao", 22.672, 106.268),
    ("CAM-03", "Đèo Khau Cốc Chà – QL34", "Khánh Xuân", 22.803, 105.724),
    ("CAM-04", "Đập tràn Thủy điện Bảo Lạc B", "Bảo Lạc", 22.966, 105.642),
    ("CAM-05", "Thác Bản Giốc – sông Quây Sơn", "Đàm Thủy", 22.855, 106.722),
    ("CAM-06", "Ngã ba Đông Khê – QL4A", "Đông Khê", 22.434, 106.436),
]

HAZARD_POINTS = [
    (
        "sat_lo",
        "do",
        "Sạt lở taluy dương đèo Khau Cốc Chà (QL34)",
        "Nứt dọc taluy dài ~40 m, đất đá có nguy cơ trượt xuống mặt đường.",
        "Khánh Xuân",
        22.806,
        105.720,
    ),
    (
        "sat_lo",
        "do",
        "Nguy cơ sạt lở cụm dân cư Nà Pồng",
        "8 hộ dân dưới chân sườn đồi dốc >35°, nứt nền nhà.",
        "Bảo Lâm",
        22.872,
        105.482,
    ),
    (
        "sat_lo",
        "cam",
        "Sạt lở đèo Mẻ Pia",
        "Đá lăn rải rác, hạn chế phương tiện qua lại ban đêm.",
        "Cô Ba",
        22.872,
        105.842,
    ),
    (
        "sat_lo",
        "cam",
        "Sạt lở khu vực mỏ thiếc Tĩnh Túc",
        "Bãi thải mỏ bão hòa nước, nguy cơ trượt.",
        "Tĩnh Túc",
        22.645,
        105.880,
    ),
    ("sat_lo", "vang", "Taluy đèo Mã Phục (QL3)", "Theo dõi nứt vỡ mép đường.", "Trà Lĩnh", 22.768, 106.287),
    ("sat_lo", "cam", "Sườn núi Phja Đén", "Lũ quét, sạt lở suối Phja Đén.", "Thành Công", 22.596, 105.848),
    (
        "sat_lo",
        "do",
        "Nguy cơ lũ quét suối Nậm Quang",
        "Suối dâng nhanh, 12 hộ ven suối.",
        "Nam Quang",
        22.790,
        105.540,
    ),
    (
        "giao_thong",
        "do",
        "Tắc đường QL34 km 212 – cây đổ + đất đá",
        "Ùn tắc 2 chiều, cần máy xúc.",
        "Phan Thanh",
        22.728,
        105.768,
    ),
    (
        "giao_thong",
        "cam",
        "Ngầm tràn Bản Ngắn nước chảy xiết",
        "Cấm phương tiện qua ngầm.",
        "Hòa An",
        22.735,
        106.170,
    ),
    (
        "ha_tang",
        "cam",
        "Đứt đường dây 35 kV Nguyên Bình – Tĩnh Túc",
        "Mất điện 3 thôn.",
        "Nguyên Bình",
        22.650,
        105.920,
    ),
    ("ha_tang", "vang", "Sụt lún mố cầu tràn Bản Giới", "Hạn chế tải trọng.", "Quảng Uyên", 22.700, 106.430),
]

# Vùng nguy hiểm động ban đầu (loại, cấp, tên, độ sâu, xã, hình học: ("line", [(lat,lon)...], bán_kính_m) | ("circle", (lat,lon), bán_kính_m))
HAZARD_ZONES = [
    (
        "ngap",
        "cam",
        "Ngập ven sông Bằng Giang – nội thị",
        1.2,
        "Thục Phán",
        (
            "line",
            [
                (22.700, 106.205),
                (22.688, 106.228),
                (22.676, 106.245),
                (22.667, 106.259),
                (22.657, 106.278),
                (22.645, 106.300),
            ],
            320,
        ),
    ),
    (
        "ngap",
        "do",
        "Ngập sâu khu Sông Bằng – Hợp Giang",
        2.1,
        "Nùng Trí Cao",
        ("line", [(22.671, 106.252), (22.664, 106.266), (22.657, 106.278)], 160),
    ),
    (
        "ngap",
        "vang",
        "Ngập ven sông Hiến – Nà Phía",
        0.6,
        "Thục Phán",
        ("line", [(22.715, 106.195), (22.700, 106.215), (22.682, 106.240)], 220),
    ),
    (
        "ngap",
        "cam",
        "Ngập hạ lưu Bằng Giang – Phục Hòa",
        1.4,
        "Phục Hòa",
        ("line", [(22.540, 106.520), (22.520, 106.550), (22.500, 106.578)], 280),
    ),
    ("sat_lo", "do", "Vùng sạt lở đèo Khau Cốc Chà", None, "Khánh Xuân", ("circle", (22.806, 105.720), 900)),
    ("sat_lo", "do", "Vùng sạt lở Nà Pồng – Pác Miầu", None, "Bảo Lâm", ("circle", (22.872, 105.482), 700)),
    (
        "lu_quet",
        "cam",
        "Vùng nguy cơ lũ quét suối Nậm Quang",
        None,
        "Nam Quang",
        ("circle", (22.790, 105.540), 1100),
    ),
]

# ---------------------------------------------------------------------------
# Mạng đường (sơ đồ đơn giản hoá, nối tâm các xã) phục vụ định tuyến an toàn
# ---------------------------------------------------------------------------
EXTRA_NODES = {
    "Cửa ngõ Bắc Kạn (QL3)": (22.520, 106.060),
    "Cửa ngõ Lạng Sơn (QL4A)": (22.335, 106.560),
    "Cửa ngõ Hà Giang (QL34)": (22.930, 105.300),
    "Đèo Khau Cốc Chà": (22.806, 105.720),
    "Đèo Mã Phục": (22.770, 106.285),
}

ROADS: list[tuple[str, list[str], float]] = [
    (
        "QL3",
        [
            "Cửa ngõ Bắc Kạn (QL3)",
            "Nguyễn Huệ",
            "Tân Giang",
            "Nùng Trí Cao",
            "Thục Phán",
            "Hòa An",
            "Đèo Mã Phục",
            "Trà Lĩnh",
        ],
        45,
    ),
    (
        "QL34",
        [
            "Thục Phán",
            "Nam Tuấn",
            "Tam Kim",
            "Nguyên Bình",
            "Tĩnh Túc",
            "Phan Thanh",
            "Đèo Khau Cốc Chà",
            "Khánh Xuân",
            "Bảo Lạc",
            "Hưng Đạo",
            "Bảo Lâm",
            "Quảng Lâm",
            "Cửa ngõ Hà Giang (QL34)",
        ],
        40,
    ),
    ("QL4A", ["Tân Giang", "Canh Tân", "Kim Đồng", "Đông Khê", "Đức Long", "Cửa ngõ Lạng Sơn (QL4A)"], 45),
    ("QL3 (Cao Bằng – Tà Lùng)", ["Nùng Trí Cao", "Bế Văn Đàn", "Quảng Uyên", "Hạnh Phúc", "Phục Hòa"], 45),
    ("QL3 (Quảng Uyên – Trùng Khánh)", ["Quảng Uyên", "Độc Lập", "Trùng Khánh", "Đàm Thủy"], 40),
    (
        "Tuyến biên giới Trà Lĩnh – Trùng Khánh",
        ["Trà Lĩnh", "Quang Trung", "Quang Hán", "Trùng Khánh", "Đình Phong", "Đàm Thủy"],
        35,
    ),
    ("ĐT Hạ Lang", ["Quảng Uyên", "Quang Long", "Hạ Lang", "Lý Quốc"], 35),
    ("ĐT Hạ Lang – Vinh Quý", ["Hạ Lang", "Vinh Quý"], 30),
    ("ĐT Trùng Khánh – Hạ Lang", ["Trùng Khánh", "Đoài Dương", "Quang Long"], 35),
    ("ĐT Hòa An – Hà Quảng", ["Hòa An", "Cần Yên", "Trường Hà", "Hà Quảng", "Tổng Cọt"], 35),
    ("ĐT Pác Bó", ["Trường Hà", "Lũng Nặm"], 30),
    ("ĐT Thông Nông", ["Cần Yên", "Thông Nông", "Thanh Long"], 30),
    ("ĐT Bạch Đằng – Quang Hán", ["Thục Phán", "Bạch Đằng", "Quang Hán"], 35),
    ("ĐT Thạch An", ["Canh Tân", "Minh Khai", "Thạch An", "Bế Văn Đàn"], 35),
    ("ĐT Phục Hòa – Đức Long", ["Phục Hòa", "Đức Long"], 35),
    ("ĐT Minh Tâm", ["Nguyễn Huệ", "Minh Tâm", "Tam Kim"], 30),
    ("ĐT Thành Công", ["Tĩnh Túc", "Thành Công", "Minh Tâm"], 25),
    ("ĐT Ca Thành", ["Phan Thanh", "Ca Thành", "Yên Thổ", "Lý Bôn"], 25),
    ("ĐT Bảo Lâm", ["Bảo Lâm", "Nam Quang", "Lý Bôn"], 30),
    ("ĐT Sơn Lộ", ["Bảo Lâm", "Sơn Lộ", "Hưng Đạo"], 25),
    ("ĐT Cốc Pàng", ["Bảo Lạc", "Cốc Pàng"], 25),
    ("ĐT Xuân Trường", ["Bảo Lạc", "Xuân Trường"], 25),
    ("ĐT Huy Giáp", ["Hưng Đạo", "Huy Giáp", "Nam Quang"], 25),
    ("ĐT Cô Ba – Thanh Long", ["Bảo Lạc", "Cô Ba", "Thanh Long", "Nguyên Bình"], 25),
    ("ĐT Khánh Xuân – Huy Giáp", ["Khánh Xuân", "Huy Giáp"], 25),
]

# ---------------------------------------------------------------------------
# Lực lượng (mã, tên, loại, cấp, xã đóng quân, chỉ huy, quân số, kỹ năng)
# ---------------------------------------------------------------------------
FORCES = [
    (
        "F-QS-01",
        "Đại đội TKCN – Bộ CHQS tỉnh",
        "quan_su",
        "tinh",
        "Thục Phán",
        "Thiếu tá Hoàng Minh Đức",
        120,
        ["lai_xuong", "boi_lan", "cuu_ho_sat_lo", "so_cuu", "cuu_ho_vung_nui"],
    ),
    (
        "F-CA-01",
        "Phòng Cảnh sát PCCC & CNCH – Công an tỉnh",
        "cong_an",
        "tinh",
        "Nùng Trí Cao",
        "Trung tá Nông Văn Toàn",
        85,
        ["lan", "lai_xuong", "cuu_ho_sat_lo", "cho_nghiep_vu", "so_cuu"],
    ),
    (
        "F-BP-01",
        "Đồn Biên phòng Đàm Thủy",
        "bien_phong",
        "xa",
        "Đàm Thủy",
        "Thiếu tá Lương Văn Hải",
        38,
        ["cuu_ho_vung_nui", "lai_xuong", "so_cuu"],
    ),
    (
        "F-BP-02",
        "Đồn Biên phòng Trà Lĩnh",
        "bien_phong",
        "xa",
        "Trà Lĩnh",
        "Thiếu tá Đàm Quốc Việt",
        36,
        ["cuu_ho_vung_nui", "so_cuu"],
    ),
    (
        "F-BP-03",
        "Đồn Biên phòng Tà Lùng",
        "bien_phong",
        "xa",
        "Phục Hòa",
        "Thiếu tá Bế Thanh Sơn",
        35,
        ["lai_xuong", "boi_lan"],
    ),
    (
        "F-BP-04",
        "Đồn Biên phòng Cốc Pàng",
        "bien_phong",
        "xa",
        "Cốc Pàng",
        "Đại úy Triệu Văn Nam",
        30,
        ["cuu_ho_vung_nui", "cuu_ho_sat_lo"],
    ),
    (
        "F-KV-01",
        "Ban CHQS khu vực Bảo Lạc – Bảo Lâm",
        "quan_su",
        "tinh",
        "Bảo Lạc",
        "Trung tá Ma Văn Thành",
        60,
        ["cuu_ho_sat_lo", "cuu_ho_vung_nui", "lai_xuong"],
    ),
    (
        "F-KV-02",
        "Ban CHQS khu vực Nguyên Bình",
        "quan_su",
        "tinh",
        "Nguyên Bình",
        "Thiếu tá Hà Đức Lợi",
        45,
        ["cuu_ho_sat_lo", "cuu_ho_vung_nui"],
    ),
    (
        "F-KV-03",
        "Ban CHQS khu vực Trùng Khánh – Hạ Lang",
        "quan_su",
        "tinh",
        "Trùng Khánh",
        "Thiếu tá Lục Văn Kiên",
        45,
        ["lai_xuong", "boi_lan", "cuu_ho_vung_nui"],
    ),
    (
        "F-KV-04",
        "Ban CHQS khu vực Thạch An – Quảng Hòa",
        "quan_su",
        "tinh",
        "Đông Khê",
        "Thiếu tá Nông Đức Thắng",
        42,
        ["cuu_ho_sat_lo", "lai_xuong"],
    ),
    (
        "F-DQ-01",
        "Trung đội dân quân cơ động phường Tân Giang",
        "dan_quan",
        "xa",
        "Tân Giang",
        "Xã đội trưởng Lý Văn Hùng",
        25,
        ["lai_xuong", "boi_lan"],
    ),
    (
        "F-DQ-02",
        "Dân quân thường trực xã Hòa An",
        "dan_quan",
        "xa",
        "Hòa An",
        "Xã đội trưởng Hoàng Văn Chiến",
        20,
        ["lai_xuong", "boi_lan"],
    ),
    (
        "F-DQ-03",
        "Dân quân thường trực xã Tĩnh Túc",
        "dan_quan",
        "xa",
        "Tĩnh Túc",
        "Xã đội trưởng Triệu Tài Phú",
        18,
        ["cuu_ho_sat_lo"],
    ),
    (
        "F-DQ-04",
        "Dân quân thường trực xã Bảo Lâm",
        "dan_quan",
        "xa",
        "Bảo Lâm",
        "Xã đội trưởng Sầm Văn Quý",
        18,
        ["cuu_ho_sat_lo", "cuu_ho_vung_nui"],
    ),
    (
        "F-DQ-05",
        "Dân quân thường trực xã Quảng Uyên",
        "dan_quan",
        "xa",
        "Quảng Uyên",
        "Xã đội trưởng Mông Văn Tiến",
        18,
        ["lai_xuong"],
    ),
    (
        "F-YT-01",
        "Trung tâm Cấp cứu 115 Cao Bằng",
        "y_te",
        "tinh",
        "Thục Phán",
        "BSCKII Nông Thị Hạnh",
        30,
        ["so_cuu", "y_te"],
    ),
    (
        "F-YT-02",
        "Đội cơ động y tế Bảo Lạc",
        "y_te",
        "xa",
        "Bảo Lạc",
        "BS Lâm Văn Tuấn",
        12,
        ["so_cuu", "y_te"],
    ),
    (
        "F-TN-01",
        "Đội tình nguyện CNCH – Hội Chữ thập đỏ tỉnh",
        "tinh_nguyen",
        "tinh",
        "Tân Giang",
        "Ông Đinh Văn Khánh",
        40,
        ["so_cuu", "boi_lan"],
    ),
]

# (mã, tên, loại, nhóm, mã lực lượng, sức chở)
VEHICLES = [
    ("CB-X01", "Xuồng cao tốc X01", "xuong", "duong_thuy", "F-QS-01", 8),
    ("CB-X02", "Xuồng cao tốc X02", "xuong", "duong_thuy", "F-QS-01", 8),
    ("CB-X03", "Xuồng cao tốc X03", "xuong", "duong_thuy", "F-CA-01", 8),
    ("CB-X04", "Xuồng cao tốc X04", "xuong", "duong_thuy", "F-DQ-01", 6),
    ("CB-X05", "Xuồng cao tốc X05", "xuong", "duong_thuy", "F-DQ-02", 6),
    ("CB-X06", "Xuồng composite X06", "xuong", "duong_thuy", "F-BP-03", 6),
    ("CB-X07", "Xuồng cao tốc X07", "xuong", "duong_thuy", "F-KV-03", 6),
    ("CB-X08", "Xuồng cao tốc X08", "xuong", "duong_thuy", "F-DQ-05", 6),
    ("CB-CN01", "Ca nô Biên phòng CN01", "ca_no", "duong_thuy", "F-BP-01", 12),
    ("CB-G01", "Ghe dân sự đăng ký dự phòng G01", "ghe", "duong_thuy", "F-DQ-02", 5),
    ("CB-LN01", "Xe lội nước LN01", "xe_loi_nuoc", "duong_bo", "F-QS-01", 12),
    ("CB-LN02", "Xe lội nước LN02", "xe_loi_nuoc", "duong_bo", "F-CA-01", 12),
    ("CB-BT01", "Xe bọc thép BTR-152", "xe_boc_thep", "duong_bo", "F-QS-01", 10),
    ("CB-T01", "Xe tải gầm cao T01", "xe_tai", "duong_bo", "F-QS-01", 20),
    ("CB-T02", "Xe tải gầm cao T02", "xe_tai", "duong_bo", "F-KV-01", 20),
    ("CB-T03", "Xe tải gầm cao T03", "xe_tai", "duong_bo", "F-KV-02", 20),
    ("CB-T04", "Xe tải gầm cao T04", "xe_tai", "duong_bo", "F-KV-04", 20),
    ("CB-T05", "Xe tải cứu trợ T05", "xe_tai", "duong_bo", "F-TN-01", 16),
    ("CB-MX01", "Máy xúc bánh xích MX01", "may_xuc", "duong_bo", "F-KV-01", None),
    ("CB-MX02", "Máy xúc MX02", "may_xuc", "duong_bo", "F-KV-02", None),
    ("CB-MX03", "Máy xúc MX03", "may_xuc", "duong_bo", "F-CA-01", None),
    ("CB-MX04", "Máy xúc MX04", "may_xuc", "duong_bo", "F-DQ-04", None),
    ("CB-MU01", "Máy ủi MU01", "may_ui", "duong_bo", "F-KV-04", None),
    ("CB-CT01", "Xe cứu thương 115-01", "xe_cuu_thuong", "duong_bo", "F-YT-01", 2),
    ("CB-CT02", "Xe cứu thương 115-02", "xe_cuu_thuong", "duong_bo", "F-YT-01", 2),
    ("CB-CT03", "Xe cứu thương Bảo Lạc", "xe_cuu_thuong", "duong_bo", "F-YT-02", 2),
    ("CB-PD01", "Máy phát điện 50 kVA", "may_phat_dien", "thiet_bi", "F-QS-01", None),
    ("CB-PD02", "Máy phát điện 30 kVA", "may_phat_dien", "thiet_bi", "F-KV-02", None),
    ("CB-MC01", "Máy cưa cắt chuyên dụng", "may_cua", "thiet_bi", "F-CA-01", None),
    ("CB-FC01", "Flycam dò tìm FC01", "flycam", "thiet_bi", "F-CA-01", None),
    ("CB-FC02", "Flycam nhiệt FC02", "flycam", "thiet_bi", "F-KV-01", None),
    ("CB-FC03", "Flycam FC03", "flycam", "thiet_bi", "F-BP-04", None),
    ("CB-BTS01", "Trạm BTS lưu động Viettel", "bts_luu_dong", "thiet_bi", "F-QS-01", None),
    ("CB-BTS02", "Trạm BTS lưu động VNPT", "bts_luu_dong", "thiet_bi", "F-KV-01", None),
]

ITEMS = [
    ("MI_TOM", "Mì tôm", "luong_thuc", "thùng"),
    ("GAO", "Gạo", "luong_thuc", "tấn"),
    ("LUONG_KHO", "Lương khô", "luong_thuc", "thùng"),
    ("NUOC_CHAI", "Nước đóng chai", "nuoc_uong", "thùng"),
    ("TUI_SO_CUU", "Túi sơ cứu", "y_te", "túi"),
    ("THUOC_CO_BAN", "Cơ số thuốc cơ bản", "y_te", "cơ số"),
    ("CLORAMIN_B", "Cloramin B", "y_te", "kg"),
    ("PHAO_CUU_SINH", "Phao tròn cứu sinh", "do_dung", "chiếc"),
    ("AO_PHAO", "Áo phao", "do_dung", "chiếc"),
    ("CHAN_MAN", "Chăn màn", "do_dung", "bộ"),
    ("DEN_PIN", "Đèn pin", "do_dung", "chiếc"),
    ("BAT_TRAI", "Bạt che", "do_dung", "tấm"),
]

# Định mức an toàn cơ sở (nhân hệ số theo cấp kho)
ITEM_QUOTA = {
    "MI_TOM": 800,
    "GAO": 12,
    "LUONG_KHO": 400,
    "NUOC_CHAI": 900,
    "TUI_SO_CUU": 150,
    "THUOC_CO_BAN": 60,
    "CLORAMIN_B": 80,
    "PHAO_CUU_SINH": 120,
    "AO_PHAO": 400,
    "CHAN_MAN": 300,
    "DEN_PIN": 200,
    "BAT_TRAI": 250,
}

# (mã, tên, cấp, xã)
WAREHOUSES = [
    ("K-TINH", "Kho dự trữ PCTT tỉnh Cao Bằng", "tinh", "Tân Giang"),
    ("K-HA", "Kho cụm Hòa An", "cum", "Hòa An"),
    ("K-TA", "Kho cụm Thạch An", "cum", "Đông Khê"),
    ("K-QH", "Kho cụm Quảng Hòa", "cum", "Quảng Uyên"),
    ("K-TK", "Kho cụm Trùng Khánh", "cum", "Trùng Khánh"),
    ("K-HL", "Kho cụm Hạ Lang", "cum", "Hạ Lang"),
    ("K-HQ", "Kho cụm Hà Quảng", "cum", "Trường Hà"),
    ("K-NB", "Kho cụm Nguyên Bình", "cum", "Nguyên Bình"),
    ("K-BLAC", "Kho cụm Bảo Lạc", "cum", "Bảo Lạc"),
    ("K-BLAM", "Kho cụm Bảo Lâm", "cum", "Bảo Lâm"),
    ("K-DC-01", "Kho dã chiến Khau Cốc Chà", "da_chien", "Khánh Xuân"),
]

EVAC_SITES = [
    ("Trường THPT Chuyên Cao Bằng", "truong_hoc", "Thục Phán", 600),
    ("Nhà Văn hóa tổ 5 phường Thục Phán", "nha_van_hoa", "Thục Phán", 150),
    ("Trường THCS Hợp Giang", "truong_hoc", "Nùng Trí Cao", 400),
    ("Trung tâm Văn hóa tỉnh", "nha_van_hoa", "Nùng Trí Cao", 800),
    ("Trường Cao đẳng Sư phạm Cao Bằng", "truong_hoc", "Tân Giang", 700),
    ("Trường THPT Hòa An", "truong_hoc", "Hòa An", 500),
    ("Nhà Văn hóa xã Bạch Đằng", "nha_van_hoa", "Bạch Đằng", 200),
    ("Trường PTDTNT Nguyên Bình", "truong_hoc", "Nguyên Bình", 450),
    ("Trường THCS Tĩnh Túc", "truong_hoc", "Tĩnh Túc", 300),
    ("Nhà Văn hóa xã Phan Thanh", "nha_van_hoa", "Phan Thanh", 150),
    ("Trường THPT Bảo Lạc", "truong_hoc", "Bảo Lạc", 500),
    ("Trụ sở UBND xã Khánh Xuân", "tru_so", "Khánh Xuân", 120),
    ("Trường PTDTNT Bảo Lâm", "truong_hoc", "Bảo Lâm", 450),
    ("Nhà Văn hóa xã Nam Quang", "nha_van_hoa", "Nam Quang", 150),
    ("Trường THCS Lý Bôn", "truong_hoc", "Lý Bôn", 250),
    ("Trường THPT Trùng Khánh", "truong_hoc", "Trùng Khánh", 500),
    ("Trường THPT Quảng Uyên", "truong_hoc", "Quảng Uyên", 450),
    ("Trường THPT Phục Hòa", "truong_hoc", "Phục Hòa", 400),
    ("Doanh trại Đồn BP Tà Lùng", "doanh_trai", "Phục Hòa", 200),
    ("Trường THPT Thạch An", "truong_hoc", "Đông Khê", 400),
    ("Trường THPT Hà Quảng", "truong_hoc", "Trường Hà", 400),
    ("Trường THPT Hạ Lang", "truong_hoc", "Hạ Lang", 350),
    ("Nhà Văn hóa xã Ca Thành", "nha_van_hoa", "Ca Thành", 120),
    ("Trường THCS Yên Thổ", "truong_hoc", "Yên Thổ", 200),
]

PLACE_NAMES = [
    ("Thác Bản Giốc", "dia_danh", "Đàm Thủy", 22.855, 106.723),
    ("Động Ngườm Ngao", "dia_danh", "Đàm Thủy", 22.846, 106.708),
    ("Khu di tích Pác Bó", "dia_danh", "Trường Hà", 22.980, 106.047),
    ("Chợ Xanh Cao Bằng", "cong_trinh", "Thục Phán", 22.665, 106.256),
    ("Cầu Bằng Giang", "cong_trinh", "Thục Phán", 22.667, 106.259),
    ("Cửa khẩu Tà Lùng", "cong_trinh", "Phục Hòa", 22.488, 106.586),
    ("Cửa khẩu Trà Lĩnh", "cong_trinh", "Trà Lĩnh", 22.842, 106.330),
    ("Hồ Thang Hen", "dia_danh", "Quang Trung", 22.790, 106.345),
    ("Đèo Mã Phục", "deo", "Trà Lĩnh", 22.770, 106.285),
    ("Đèo Khau Cốc Chà", "deo", "Khánh Xuân", 22.806, 105.720),
    ("Đèo Mẻ Pia", "deo", "Cô Ba", 22.872, 105.842),
    ("Đèo Cao Bắc", "deo", "Phan Thanh", 22.705, 105.800),
    ("Núi Phja Oắc", "dia_danh", "Thành Công", 22.605, 105.880),
    ("Mỏ thiếc Tĩnh Túc", "cong_trinh", "Tĩnh Túc", 22.645, 105.878),
    ("Thôn Nà Pồng", "thon", "Bảo Lâm", 22.872, 105.482),
    ("Thôn Nà Luông", "thon", "Nam Quang", 22.788, 105.538),
    ("Tổ dân phố Sông Bằng", "thon", "Nùng Trí Cao", 22.663, 106.268),
    ("Tổ dân phố Hợp Giang", "thon", "Thục Phán", 22.671, 106.253),
    ("Thôn Bản Ngắn", "thon", "Hòa An", 22.735, 106.170),
    ("Thôn Khuổi Kỉn", "thon", "Khánh Xuân", 22.812, 105.705),
    ("Thôn Nà Pò", "thon", "Phục Hòa", 22.505, 106.572),
    ("Thôn Pác Rà", "thon", "Tĩnh Túc", 22.650, 105.862),
]

# Email demo: <username>@caobang-pctt.local (nhận link đặt lại mật khẩu qua Mailpit khi chạy dev)
DEMO_EMAIL_DOMAIN = "caobang-pctt.local"

# Tài khoản demo: (username, họ tên, chức vụ, mật khẩu, PIN phê duyệt, vai trò RBAC, phạm vi)
# Phạm vi: "*" toàn tỉnh · "<CUM>/*" cả cụm (địa bàn huyện cũ) · "<CUM>/<MA_XA>" một xã
USERS = [
    ("admin", "Quản trị hệ thống", "Kỹ sư vận hành hệ thống", "admin123", "0000", "super_admin", "*"),
    (
        "chihuy",
        "Hoàng Đức Chỉ",
        "Phó Trưởng ban Thường trực BCH PCTT & TKCN tỉnh",
        "chihuy123",
        "2468",
        "truong_ban",
        "*",
    ),
    (
        "admin.tinh",
        "Đàm Thị Quản",
        "Quản trị hệ thống cấp tỉnh – Văn phòng BCH",
        "admintinh123",
        None,
        "admin_tinh",
        "*",
    ),
    ("admin.coba", "Lục Văn Xã", "Quản trị xã Cô Ba", "admincoba123", None, "admin_xa", "BAOLAC/CB-COBA"),
    (
        "admin.cathan",
        "Hoàng Văn Sạt",
        "Quản trị xã Ca Thành",
        "admincathan123",
        None,
        "admin_xa",
        "NGUYENBINH/CB-CATHANH",
    ),
    (
        "admin.thucphan",
        "Nông Thị Phố",
        "Quản trị phường Thục Phán",
        "adminthucphan123",
        None,
        "admin_xa",
        "TPCAOBANG/CB-THUCPHAN",
    ),
    ("trucban", "Nông Văn Trực", "Cán bộ trực ban Văn phòng BCH tỉnh", "trucban123", None, "truc_ban", "*"),
    ("chihuy.baolac", "Ma Văn Thành", "Chỉ huy cụm Bảo Lạc", "baolac123", "1357", "chi_huy_cum", "BAOLAC/*"),
    ("canbo.coba", "Triệu Thị Mai", "Cán bộ PCTT xã Cô Ba", "coba123", None, "can_bo_xa", "BAOLAC/CB-COBA"),
    ("thukho", "Lý Văn Kho", "Thủ kho dự trữ PCTT tỉnh", "thukho123", None, "thu_kho", "*"),
    ("xem", "Tài khoản xem", "Lãnh đạo Sở ngành", "xem123", None, "quan_sat", "*"),
]

TEMPLATES = [
    (
        "XA_LU",
        "Hồ chứa xả lũ",
        "cam",
        "[BCH PCTT Cao Bằng] {ten_ho} xả lũ lưu lượng {luu_luong} m3/s từ {thoi_gian}. Người dân ven sông {song} thuộc {dia_diem} "
        "tuyệt đối không qua ngầm tràn, không vớt củi, đánh bắt cá; di chuyển tài sản lên cao. Hotline: 112.",
        ["ten_ho", "luu_luong", "thoi_gian", "song", "dia_diem"],
    ),
    (
        "SAT_LO",
        "Yêu cầu di dời do sạt lở",
        "do",
        "[KHẨN CẤP] Nguy cơ sạt lở đất RẤT CAO tại {dia_diem}. Lượng mưa tích lũy {luong_mua} mm. Yêu cầu các hộ dân dưới "
        "taluy, sườn đồi di dời ngay đến {diem_so_tan} trước {thoi_gian}. Hotline: 112.",
        ["dia_diem", "luong_mua", "diem_so_tan", "thoi_gian"],
    ),
    (
        "LU_QUET",
        "Cảnh báo lũ quét",
        "do",
        "[KHẨN CẤP] Nguy cơ lũ quét trên suối {ten_suoi} ({dia_diem}) trong {so_gio} giờ tới. Không ở lại nhà ven suối, "
        "không qua suối, ngầm tràn. Di chuyển đến {diem_so_tan}. Hotline: 112.",
        ["ten_suoi", "dia_diem", "so_gio", "diem_so_tan"],
    ),
    (
        "NGAP",
        "Cảnh báo lũ, ngập lụt",
        "cam",
        "[BCH PCTT Cao Bằng] Lúc {thoi_gian}, mực nước sông {song} tại {tram} đạt {muc_nuoc} m, trên Báo động {cap_bao_dong}. "
        "Nhân dân {dia_diem} chủ động kê kích tài sản, sẵn sàng sơ tán. Hotline: 112.",
        ["thoi_gian", "song", "tram", "muc_nuoc", "cap_bao_dong", "dia_diem"],
    ),
    (
        "CHUAN_BI_SO_TAN",
        "Chuẩn bị sơ tán (theo dự báo)",
        "vang",
        "[BCH PCTT Cao Bằng] Dự báo {so_gio} giờ tới khu vực {dia_diem} có mưa rất to, nguy cơ {nguy_co}. Đề nghị nhân dân "
        "chuẩn bị lương thực, giấy tờ, sẵn sàng sơ tán theo hướng dẫn của chính quyền.",
        ["so_gio", "dia_diem", "nguy_co"],
    ),
    (
        "BAO_ATND",
        "Bão / Áp thấp nhiệt đới",
        "cam",
        "[BCH PCTT Cao Bằng] Do ảnh hưởng hoàn lưu {ten_bao}, từ {thoi_gian} tỉnh Cao Bằng có mưa to đến rất to {luong_mua} mm. "
        "Nguy cơ cao lũ quét, sạt lở tại {dia_diem}. Hạn chế ra ngoài, không qua ngầm tràn.",
        ["ten_bao", "thoi_gian", "luong_mua", "dia_diem"],
    ),
]

# Mẫu tin nhắn cầu cứu dùng cho bộ mô phỏng (sẽ đi qua bộ bóc tách NLP)
SOS_MESSAGES = [
    (
        "ZALO",
        "Cứu với! Nhà tôi ở tổ Sông Bằng phường Nùng Trí Cao nước ngập lên tận mái, có 4 người trong đó 1 cụ già 80 tuổi.",
    ),
    (
        "HOTLINE",
        "Sạt lở đất vùi một phần nhà ở thôn Nà Pồng xã Bảo Lâm, 2 người bị thương nặng, cần cấp cứu gấp.",
    ),
    ("APP", "Nước suối dâng nhanh ở Nam Quang, 6 người mắc kẹt bên kia suối không về được, có trẻ em."),
    ("ZALO", "Thôn Bản Ngắn xã Hòa An ngập sâu 1.5m, 3 hộ cần xuồng di dời người già và trẻ nhỏ."),
    ("HOTLINE", "Đèo Khau Cốc Chà sạt lở, 1 xe khách bị kẹt, khoảng 12 người, chưa có ai bị thương."),
    ("ZALO", "Xã Phục Hòa thôn Nà Pò hết lương thực và nước sạch 2 ngày nay, 15 hộ cần tiếp tế."),
    ("APP", "Nhà ở tổ Hợp Giang phường Thục Phán bị ngập, 5 người trên gác, cần hỗ trợ."),
    ("HOTLINE", "Tĩnh Túc thôn Pác Rà có sụt lún nứt nhà, 3 hộ xin hỗ trợ di dời khẩn."),
    ("ZALO", "Bà bầu sắp sinh bị cô lập do ngập tại xã Bạch Đằng, cần cấp cứu y tế."),
    ("APP", "Lũ quét cuốn trôi cầu tạm xã Ca Thành, 8 người mắc kẹt trên đồi."),
    ("HOTLINE", "Nhà sập do mưa lớn ở xã Yên Thổ, 1 người bị mắc kẹt bên trong."),
    ("ZALO", "Xã Đàm Thủy nước sông Quây Sơn lên nhanh, 4 hộ ven sông cần di dời."),
]

# Ghi chú: tên chỉ huy/cán bộ là giả định; số điện thoại dùng đầu số 0999 (không cấp phát) cho an toàn khi demo.
DEMO_PHONE_PREFIX = "0999"
